### ISSUE TITLE
Is there a /xf * Exclude all files option?

### ISSUE THREAD

**Issue by yyh1002** [Cinchoo/ChoEazyCopy#12]
Trying to copy directories only. Thanks.

**Comment by Cinchoo** [comment]
This option may help 

![image](https://user-images.githubusercontent.com/9448455/103382507-49102000-4abd-11eb-8aed-a51f67cc15b4.png)

**Comment by yyh1002** [comment]
It worked. Thank you. Just had to put * in the box. 
I only saw people saying to put /xf * but didn't understand the meaning. 
So it means excluding files with any name.
