### ISSUE TITLE
64-Bit?

### ISSUE THREAD

**Issue by Thundros** [Cinchoo/ChoEazyCopy#14]
Hi, @Cinchoo! First off, I'd like to say : HATS OFF TO YOU, BROTHER! This software is INCREDIBLY fast, I can transfer gigs & gigs of data in under 10 minutes! Second, I'd just like to ask that perhaps you can provide a 64-bit version of this so it never freezes until it updates in order to watch the file list in real time among other good things as well.

Once again, THANK YOU & CONGRATULATIONS on the AWESOME program! <3

**Comment by Cinchoo** [comment]
Thanks for your feedback.

This application is build under 'Any CPU' mode, it means it runs in both 32 bit / 64 bit environments.

**Comment by Thundros** [comment]
@Cinchoo : Ah, excellent! Is there any reason why it's not scrolling when I have the scrolling box checked? Once again, thank you! :)

**Comment by Cinchoo** [comment]
it is working!. Not sure why it is not for u.
