### ISSUE TITLE
No output entry during copying

### ISSUE THREAD

**Issue by AsUn-bxxO** [Cinchoo/ChoEazyCopy#15]
ChoEazyCopy 1.0.0.9 does not show output entry during copying. Best you can see immediately when 1 folder with 1 file (20 GB image) copied to the desktop. It shows during the copy no live output, in Output everything is empty. When after a few seconds later the copy process is finished, it shows the full output report. But I want to see live output and not the final report.

I only use the default settings and use Windows 8.1.

**Comment by Cinchoo** [comment]
Yes it is a bug, was introduced while adding throttle behavior to avoid UI freeze. Will apply fix shortly.

**Comment by Cinchoo** [comment]
put a fix, released v1.0.0.10. 

Try and let me know. Thx.

**Comment by AsUn-bxxO** [comment]
> put a fix, released v1.0.0.10.
> 
> Try and let me know. Thx.

Not working. Always the same bug.

**Comment by Cinchoo** [comment]
put a fix again, updated the binary v1.0.0.10.

let me know if that fix the issue. thx

**Comment by AsUn-bxxO** [comment]
Thank you, it works.
