### ISSUE TITLE
The "Run" icon is very pixelated

### ISSUE THREAD

**Issue by AsUn-b2xxO7** [Cinchoo/ChoEazyCopy#16]
Hello can you update the "Run" icon with high resolution graphics?

It looks very pixelated on my Full HD monitor.

**Comment by Cinchoo** [comment]
Got it, updated with new image. v1.0.0.10

try and let me know.

**Comment by AsUn-bxxO** [comment]
@Cinchoo 
Thanks it looks much higher resolution now.

What do you say to the big icon e.g "New", " "Donate", "NEW" and the other small icons? I think all of them should be brought to current resolution or do you think it's not pixelated?

Other question ChoEazyCopy aren't you going to switch to Microsoft Fluent Design (as theme)?

**Comment by Cinchoo** [comment]
Fixed other 2 icons as well (v1.0.0.10)

Will look into fluent design later.

**Comment by AsUn-bxxO** [comment]
> Fixed other 2 icons (new, donate) as well (v1.0.0.10). Others I'll leave them for now.

Thank you can you provide the version now?

> Will look into fluent design later.

Very good.

**Comment by Cinchoo** [comment]
Updated to v1.0.0.10
