### ISSUE TITLE
Unable to de-select /mt option

### ISSUE THREAD

**Issue by mwrobbo** [Cinchoo/ChoEazyCopy#19]
If I want to throttle the copy by using the /IPG (inter-packet gap) option then you need to be able to de-select the /MT (multi-threading) value as the two cant be used together.

Currently the lowest value I can set it to is 1. If I go any lower then it resets to the default of 8. 
If I type in 0 then it resets to number 8.

**Comment by Cinchoo** [comment]
Applied fix. 
take the release v1.0.0.11

**Comment by guy-rouillier** [comment]
Just set the number of threads to zero, and the MT option will be removed.
