### ISSUE TITLE
quit unexpectedly, resulting in a messy file 

### ISSUE THREAD

**Issue by ZKBL** [Cinchoo/ChoEazyCopy#22]
Hello, @Cinchoo I was using choeasycopy to copy a file and the program quit unexpectedly, resulting in a messy file that I can't see anymore, is there a solution for this?

The file now looks like the image below

![image](https://user-images.githubusercontent.com/18417140/107598700-88539400-6c59-11eb-87a2-f3c919af6177.png)

![image](https://user-images.githubusercontent.com/18417140/107598758-b638d880-6c59-11eb-9cf4-1725e2a71f73.png)

**Comment by Cinchoo** [comment]
Pls consider using the /UNILOG option. and turn off /UNICODE option. Give a try, let me know.

**Comment by ZKBL** [comment]
I lost the data because of my improper operation, but thank you for your help!
