### ISSUE TITLE
Question - zip files at destination 

### ISSUE THREAD

**Issue by stephen147** [Cinchoo/ChoEazyCopy#23]
I was hoping to use this for setting an automated backup of a drive. 

I was hoping to zip each file that's copied over to the destination. 

Is that possible?

**Comment by Cinchoo** [comment]
Yes, you can. Pass zip command / batch file at `PostCommands` parameter, which gets executed after robocopy completes

![image](https://user-images.githubusercontent.com/9448455/108573569-f85dbc00-72e2-11eb-9beb-81501ef1db61.png)

**Comment by stephen147** [comment]
Thanks. Would this be something that could be added to the program?

Which zip program performs best here?

**Comment by Cinchoo** [comment]
No, this is free style text. You can add commands whatever u needs.
