### ISSUE TITLE
Microsoft Defender SmartScreen blocks unknown app

### ISSUE THREAD

**Issue by cpetry** [Cinchoo/ChoEazyCopy#24]
My defender blocks the app and warns of risks.
Can this app somehow be recognized as "safe"?

**Comment by Cinchoo** [comment]
You need to setup your device to allow such programs to run without blocking by defender. Below links may help 

https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-set-individual-device
https://www.windowscentral.com/how-fix-app-has-been-blocked-your-protection-windows-10

**Comment by cpetry** [comment]
I am aware of that. I meant if there is a possibility for you to be a "known" or safe developer to Microsoft.
Being recognized by defender so to say.

**Comment by Cinchoo** [comment]
this is will require signing the application with third party and involves $$$. Can't do it.
