### ISSUE TITLE
Remember window size and position

### ISSUE THREAD

**Issue by dfv54gdmsnsecfzsmfwhermkml** [Cinchoo/ChoEazyCopy#25]
It would be very good if there could be an option where the user can activate the option: remember window size and position.

**Comment by Cinchoo** [comment]
v1.0.0.16 has fix for this request. Try and let me know.

**Comment by dfv54gdmsnse** [comment]
> v1.0.0.16 has fix for this request. Try and let me know.

It works and how can I disable it when I no longer need it and want the default size and position (when I first launch the software)?

**Comment by Cinchoo** [comment]
v1.0.0.17 has fix for it. Try it.
