### ISSUE TITLE
Add a current created time, access time and modified time to your .zip file

### ISSUE THREAD

**Issue by dfv54gdmsnse** [Cinchoo/ChoEazyCopy#26]
As you probably know .zip stores these 3 timestamps (created time, modified time and access time), these 3 timestamps are supported by Windows system since Windows XP (2001) for the users.

It would be good if you store a current timestamp in the .zip file when updating. Additionally the zip file name should have a version number.

The logic should be. Created time is never later than modified time. Access time has the same time as modified time.

Windows system default behavior is known to set created time very often illogically and it happens very often that created time is later than modified time. An example is if you create a .txt file today and 1 day later you use Windows Explorer to copy this .txt file to an external hard drive. then the copied .txt file has a different created time and this is the transfer time and not the from the source. This is also the reason why I don't use Windows Explorer and prefer to use robocopy (GUI).

---
Other question do you know if robocopy keeps the nanoseconds for created time, modified time and access time?

NTFS supports nanoseconds (accuracy of 100), but I don't know any free file manager (GUI) that shows the nanoseconds for NTFS, can you help?

**Comment by Cinchoo** [comment]
this request is out of scope. Wont fix. thx.

**Comment by dfv54gdmsnse** [comment]
Why is this not possible? Is this due to Micrsofort programming software? I think the Windows system generally supports this.
