### ISSUE TITLE
ChoEazyCopy GUI "frozen" - taking hours to give back control after quick & successful transfer

### ISSUE THREAD

**Issue by xavpitz** [Cinchoo/ChoEazyCopy#30]
Hello,

I'm experiencing a "strange" problem.
I'm using ChoEazyCopy to transfer big chunks of data from an old CIFS server to a new CIFS server.

Those chunks can range from 10GB of data to 300+GB of data.
Any way I proceed the transfers are as as quick & as successful as expected, but...

When transferring large chunks 50GB+ with 100.000+ files & folders, the GUI takes more & more time after the transfer to be responsive again. In the meantime I see a ChoEazyCopy process in the task manager that can take up to 10% of CPU even if the transfers are well completed since minutes/hours.
It seems to me like, depending on the amount of files/directories that have been processed, the GUI takes up an exponential time to be clickable again. I'm very interested in being able to retrieve the output log to deliver it as proof that all the data has successfully being copied.

The last transfer that I did was 351GB of data, 481.737 files & 419.580 folders.
As I am transferring at 800Mbits/sec it takes about 1 hour to complete the whole copy job.
I'm very happy about the transfer speed, my issue is that 15 hours later, I'm still not able to click in the GUI to retrieve the log file...

The more complex the data being processed is, the longer (it feels exponential) the time it needs to give control back.
For 10-20 Gigs it is instantaneous,
For 100 Gigs it takes minutes (almost an hour)
For 351 GBs, 15 hours and it still didnt't give me control back.

Tool is installed on a Win2019 VM, 16vCPUs, 32GB memory, vmxnet3 virtual NIC (physically 10 GbE capable in the background).
.NET installed :
PSChildName Version
----------- -------
Client      4.8.03761
Full        4.8.03761
Client      4.0.0.0

I wonder if others are experiencing the same problem.
I have the same issue with a Windows 2012 VM (similar specs) running .NET 4.7

Best Regards,

Xavier

**Comment by Cinchoo** [comment]
Thanks for reporting it, its hard for me to reproduce it on my local. Can you pls try this option and see if it works

![image](https://user-images.githubusercontent.com/9448455/127498364-6e103393-74f2-4fd8-a21b-54bccb604420.png)

**Comment by Cinchoo** [comment]
made few enhancements to the binary and released (v1.0.0.18) it, hope it fixes this issue. Pls try it and let me know. Thanks

**Comment by Thundros** [comment]
@Cinchoo Funny someone already mentioned this. I was gonna post about it today. The more amount of Data I'm transferring, the more my program freezes & I have to purposely crash it after the full transfer is complete.

**Comment by Cinchoo** [comment]
did you try the latest release?
