### ISSUE TITLE
Deleting main folder option?

### ISSUE THREAD

**Issue by Thundros** [Cinchoo/ChoEazyCopy#31]
@Cinchoo : So I have this option selected ( Move files & directories then delete originals ) in the screenshot below, & for some reason it's deleting my main directory automatically. In this instance, I don't want that because it's Windows' main "Downloads" folder. Therefore, I would like to ask if you could make an option that either allows or disallows the deletion of the original main directory that gets deleted after copying all the data over to the new file / directory location.

![image](https://user-images.githubusercontent.com/32390102/127754372-37ec5837-8401-4d6d-92cc-d3fe1f458622.png)

**Comment by Cinchoo** [comment]
Robocopy only offers those 2 options

<html>
<body>


/mov | Moves files, and deletes them from the source after they are copied.
-- | --
/move | Moves files and directories, and deletes them from the source after they are copied.


</body>
</html>

If your req not fall into these categories, but you can fix it by adding your custom scripts `Postcommands`


![image](https://user-images.githubusercontent.com/9448455/127771785-5c5030a8-dd43-4d1c-b269-272e11717b5a.png)

**Comment by Thundros** [comment]
@Cinchoo : What commands would I use to prevent the deletion of the main folder but delete everything else inside that folder?

**Comment by Cinchoo** [comment]
you can use 

`del /S C:\Path\to\directory\*`

**Comment by Thundros** [comment]
@Cinchoo : Is there a way I can automate the directory instead of having to put it in every time I want to keep the main folder from being deleted? Thanks!

**Comment by Cinchoo** [comment]
Afraid not.

**Comment by Thundros** [comment]
@Cinchoo : is there a way to pass parameters to your program with another program?

**Comment by Cinchoo** [comment]
No. Can u brief how are you planning automate?

**Comment by Thundros** [comment]
Well I was just gonna pass the line you showed me above into EazyCopy with my own program in order to automate which main directory needs to be preserved.. But truth be told, this would be much easier if I could just automate choosing whether or not EazyCopy deletes my main directory along WITH all folders & files contained within it.

**Comment by Cinchoo** [comment]
Well, in this case you can run the delete folder command from your program right after robocopy completes its operation.

**Comment by Thundros** [comment]
Who else thinks this should be a feature? <3 I LOVE this program & use it EVERY day & only wish to see it grow!

**Comment by Cinchoo** [comment]
Hi, put enhancement to the tool to pre and post commands parametrizable with src / dest directories using {{SRC_DIR}} / {{DEST_DIR}} tokens respectively. Let me know this helps.

**Comment by Thundros** [comment]
@Cinchoo How do I activate this option? Thank you!

**Comment by Cinchoo** [comment]
this is how you can use these tokens in pre/post commands

`del /S {{SRC_DIR}}/*`

**Comment by Cinchoo** [comment]
Here is the screenshot how to do it

![image](https://user-images.githubusercontent.com/9448455/150657113-e77892a9-18ae-47c8-9120-4fba69bfbef3.png)
