### ISSUE TITLE
Entering a backslash to the target path results in an "index out of bound" error and ChoEazyCopy crashes.

### ISSUE THREAD

**Issue by einhirn** [Cinchoo/ChoEazyCopy#34]
Hi, just tried to manually enter an UNC-path as target and it crashed after the first `\`. Not much more debug info than that, sorry. Can anyone reproduce the issue, or is it just me?

![How to reproduce, perhaps](https://user-images.githubusercontent.com/189249/147107064-b11e1a14-2460-4606-a14e-79f0b1b41111.png)

**Comment by Cinchoo** [comment]
Applied fix, pushed new release.

https://github.com/Cinchoo/ChoEazyCopy/releases/tag/v1.0.0.21
