### ISSUE TITLE
Suggestion: Add Swap and Test/Trial Run checkboxes to CHOOSE FOLDERS

### ISSUE THREAD

**Issue by DLBerger** [Cinchoo/ChoEazyCopy#35]
Could you add the following two checkboxes to CHOOSE FOLDERS:
1) Swap - this checkout will swap the source and destination.  It would make restoring from a backup very easy.
    If you check and uncheck Swap the source and destination should switch on the screen so you know exactly which
    way the copy is going
2) Test or Trial Run - this checkout would add the /L switch to the RoboCopy command so you can see what would happen
     if you were to run the command for real.  No files/directories would be harmed in the process

**Comment by Cinchoo** [comment]
Added, released v1.0.0.22.

**Comment by DLBerger** [comment]
Thank you
