### ISSUE TITLE
inconsitent naming of product

### ISSUE THREAD

**Issue by shoulders** [Cinchoo/ChoEazyCopy#4]
this is a minor issue but you refer to 'Easy Copy' in the title bar of the software rather than ChoEasyCopy (which is better and unique). there might be other places the proper name is not used

![image](https://user-images.githubusercontent.com/319997/34455049-5e03c020-ed6e-11e7-9589-1022d1c237d0.png)

**Comment by Cinchoo** [comment]
taken care of it. Will be avail on next release.

**Comment by aflyhorse** [comment]
should been fixed in commit fe89f92

**Comment by Cinchoo** [comment]
v1.0.0.7 will have this fix
