### ISSUE TITLE
too much can lock up the GUI and prevent robocopy working

### ISSUE THREAD

**Issue by shoulders** [Cinchoo/ChoEazyCopy#6]
unless I use the switch **/UNILOG:C:\RoboCopy\profile-copy.log** when copying user profiles ChoEasyCopy locks up. At first I thought it was error retry settings in the Robocopy but it seems if you run anything large without send stuff to a text file this causes issues.

This might be a normal response but I thought I would mention it just in case.

**Comment by Cinchoo** [comment]
v1.0.0.7 will have fix for it.
